/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./../../src/components/counter.vue')['default']
    Dropdown: typeof import('./../../src/components/Dropdown.vue')['default']
    HelloWorld: typeof import('./../../src/components/HelloWorld.vue')['default']
    Navigation: typeof import('./../../src/components/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
